### ISSUE TITLE
Unable to install due to the wrong zip folder structure opencart 2.1.0.2 - FIX

### ISSUE THREAD

**Issue by lucafilosofi** [smartsupp/plugin-opencart-journal-2#1]
The problem at least with **opencart 2.1.0.2**, is that the installation process fail beacuse of the wrong zip structure. 

now it's like this:  **"smartsupp.ocmod.zip > smartsupp.ocmod > files to install"** 

instead it shoult be **"smartsupp.ocmod.zip > files to install"**

**Comment by krsiakdaniel** [comment]
Hi, thanks for letting us know. Will look into this and fix it.

**Comment by krsiakdaniel** [comment]
Issue was fixed: https://github.com/smartsupp/smartsupp-plugin-opencart/blob/master/opencart-2000-2102/smartsupp.ocmod.zip?raw=true
