### ISSUE TITLE
Widget does not show up on custom theme - FIX

### ISSUE THREAD

**Issue by lucafilosofi** [smartsupp/plugin-opencart-journal-2#2]
in the **install.xml** file there is a modification line that point only to the **default** oc template
this will not work if one have a custom template installed that point to different folder, to fix this, use the wildcard symbol as below:

replace this line 

`<file path="catalog/view/theme/default/template/common/footer.tpl">`

with this:

`<file path="catalog/view/theme/*/template/common/footer.tpl">`

this tell ocmod to take into account all template under the theme folder...

**Comment by krsiakdaniel** [comment]
Hi, thanks for letting us know. I will pass this info to our developer to update the plugin.

**Comment by krsiakdaniel** [comment]
We will take this into consideration and possibly add it in near future to our new version.
